import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, Building2, CircleAlert, MapPin, MapPinned, Search, SlidersHorizontal } from "lucide-react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "../../layouts/DashboardLayout";
import { getAllGyms } from "../../api/gym.api";
import formatPrice from "../../components/marketplace/utils/formatPrice";

const fallbackImage = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1000";

function GymsPage() {
  const navigate = useNavigate();
  const [gyms, setGyms] = useState([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => { const timer = window.setTimeout(async () => { try { setLoading(true); setGyms(await getAllGyms()); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to load gyms."); } finally { setLoading(false); } }, 0); return () => window.clearTimeout(timer); }, []);
  const visibleGyms = useMemo(() => gyms.filter((gym) => [gym.name, gym.city, gym.state].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase().trim())), [gyms, search]);

  return <DashboardLayout><main className="mx-auto w-full max-w-6xl pb-8"><section className="overflow-hidden rounded-[28px] border border-white/[0.08] bg-[radial-gradient(circle_at_78%_20%,rgba(59,130,246,.24),transparent_30%),radial-gradient(circle_at_15%_30%,rgba(124,58,237,.2),transparent_28%),#11121a] p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-violet-300">Official memberships</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-white">Find your next gym.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Browse approved FitSwap partner gyms and buy a fresh membership directly from the gym.</p></div><div className="rounded-2xl border border-white/[0.09] bg-black/15 px-4 py-3"><p className="text-xs text-zinc-500">Partner gyms</p><p className="mt-1 text-2xl font-bold text-white">{gyms.length}</p></div></div><div className="mt-7 flex max-w-3xl flex-col gap-3 sm:flex-row"><div className="relative min-w-0 flex-1"><Search size={19} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by gym name, city, or state" className="w-full rounded-2xl border border-white/[0.1] bg-black/20 py-3.5 pl-11 pr-4 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-violet-400/60" /></div><button type="button" onClick={() => navigate("/gyms/nearby")} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-cyan-400/25 bg-cyan-500/[0.08] px-4 py-3.5 text-sm font-semibold text-cyan-100 hover:bg-cyan-500/15"><MapPinned size={18} /> Nearby map</button></div></section>{error && <div className="mt-5 flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-300"><CircleAlert size={16} />{error}</div>}<div className="mt-7 flex items-center justify-between"><div><h2 className="text-xl font-bold text-white">Explore gyms</h2><p className="mt-1 text-sm text-zinc-500">{visibleGyms.length} approved gym{visibleGyms.length === 1 ? "" : "s"} found</p></div><span className="hidden items-center gap-2 text-xs text-zinc-500 sm:flex"><SlidersHorizontal size={14} /> Verified partners only</span></div>{loading ? <div className="grid gap-5 pt-5 sm:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-80 animate-pulse rounded-2xl border border-white/[0.06] bg-white/[0.03]" />)}</div> : visibleGyms.length ? <div className="grid gap-5 pt-5 sm:grid-cols-2 xl:grid-cols-3">{visibleGyms.map((gym) => <GymCard key={gym.id} gym={gym} onOpen={() => navigate(`/gyms/${gym.id}`)} />)}</div> : <EmptyGyms search={search} />}</main></DashboardLayout>;
}

function GymCard({ gym, onOpen }) { const primaryImage = gym.images?.find((image) => image.isPrimary) || gym.images?.[0]; const lowestPrice = gym.plans?.[0]?.price; return <article className="group overflow-hidden rounded-2xl border border-white/[0.08] bg-[#11121a] transition hover:-translate-y-1 hover:border-violet-400/35"><div className="relative h-44 overflow-hidden"><img src={primaryImage?.imageUrl || fallbackImage} alt="" className="h-full w-full object-cover opacity-70 transition duration-500 group-hover:scale-105 group-hover:opacity-90" /><div className="absolute inset-0 bg-gradient-to-t from-[#11121a] via-transparent" /><span className="absolute left-3 top-3 inline-flex items-center gap-1 rounded-full bg-emerald-500/90 px-2 py-1 text-[10px] font-bold text-white"><BadgeCheck size={12} /> Approved</span></div><div className="p-5"><h2 className="truncate text-lg font-bold text-white">{gym.name}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-zinc-400"><MapPin size={14} /> {gym.city}, {gym.state}</p><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-zinc-500">{gym.description || "A verified FitSwap gym with official memberships."}</p><div className="mt-5 flex items-center justify-between border-t border-white/[0.07] pt-4"><div><p className="text-xs text-zinc-500">Plans from</p><p className="mt-1 font-bold text-white">{lowestPrice ? formatPrice(lowestPrice) : "View plans"}</p></div><button type="button" onClick={onOpen} className="inline-flex items-center gap-1.5 rounded-xl bg-violet-600 px-3 py-2 text-xs font-semibold text-white transition hover:bg-violet-500">View gym <ArrowRight size={14} /></button></div></div></article>; }
function EmptyGyms({ search }) { return <div className="mt-5 flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-white/[0.1] bg-[#11121a] p-8 text-center"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/10 text-violet-300"><Building2 size={22} /></div><h2 className="mt-4 font-semibold text-white">No gyms found</h2><p className="mt-2 text-sm text-zinc-500">{search ? "Try another gym name or location." : "Approved gyms will appear here."}</p></div>; }

export default GymsPage;
