const LISTING_STATUS = Object.freeze({
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    PAUSED: 'PAUSED',
    RESERVED: 'RESERVED',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    TRANSFER_PENDING: 'TRANSFER_PENDING',
    GYM_APPROVAL_PENDING: 'GYM_APPROVAL_PENDING',
    TRANSFER_REJECTED: 'TRANSFER_REJECTED',
    SOLD: 'SOLD',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED'
});

module.exports = {
    LISTING_STATUS
};